### PR TITLE
Update verify_message.js

### LINKED ISSUE #93: Verify message using mobile node
Hey 👋 

Currently, all nodes connected with Lightning Joule can write and verify messages perfectly. However, there are some cases where nodes happen to have an issue when calling  `verify_message.js`.

On the @mandelmonkey case. when he writes messages on lightning and then calls `verify_message.js`. He can not get his `pubkey.signed_by`.

Now, using raw `LND GRPC` he gets the following body:
```javascript
{
valid: false,
pubkey: <PUBKEY_HERE>
```

I guess `LN-SERVICE` restricts every object from `LND GRPC` where the `valid=false`

### PR DESCRIPTION
**Pull request by whiteyhat**
This pull request fixes #93

Return the valid parameter within the body to allow mobile/private nodes to verify messages to use this package for efficient auth services using lightning ⚡️

### CODE REVIEW

**Comment by alexbosworth** [comment]
if there isn't a valid signature won't it just omit the signed_by attribute?

**Comment by whiteyhat** [comment]
Not necessarily as described in https://github.com/alexbosworth/ln-service/issues/93#issuecomment-512903663

IMO, it doesn’t matter if the parameter `valid` should be renamed. 

However, I think it should be better if the option to decide the validity of the `verifyMessage.js` Should relay on the user, specially if it returns a pubkey in `signed_by`as described by @mandelmonkey in https://github.com/alexbosworth/ln-service/issues/93#issuecomment-512903663

**Comment by alexbosworth** [comment]
I don't really understand the different cases, when is valid: false but public_key is also set?

**Comment by mandelmonkey** [comment]
If I try with lncli verify message will return valid:false and the pubkey:correct pubkey, when I verify the messages and signature produced by a mobile node i.e. not in the graph as has all private channels

**Comment by mandelmonkey** [comment]
If I try with lncli verify message will return valid:false and the pubkey:correct pubkey, when I verify the messages and signature produced by a mobile node i.e. not in the graph as has all private channels


anyway I guess ln-service should mimic the result of lncli here?

here is an example done on my lncli

```
lncli verifymessage --msg "I am signing a secret number (6058) to log in Satoshis.Games platform" --sig rygugaem49aabakdrhkiqgfty9dt15emhn9e5oh3e9c5jnoo9fgssysusr6q7hbri5ynxngpuje73zxpgzfxszxej76mqnuaeqztozph
{
    "valid": false,
    "pubkey": "024ca2f9e249788eaf54e2e54b219959fcf9be12aecc553a7d7ae18ba85fae7a66"
}
```

the pubkey is the pubkey of my mobile node

**Comment by alexbosworth** [comment]
Ok thanks that is clearer

What I still don't understand is why you would want to know in this call if the node has all private channels or has some public channels

**Comment by mandelmonkey** [comment]
yeah I was asking the same thing on LND slack but didnt get an answer maybe
I should ask roasbeef

**Comment by alexbosworth** [comment]
Cool, yeah I think it might just be unnecessary on the lnd side

If I were to upgrade this method I might make the entire thing happen on the client side since it is just doing public key recovery on the signature, which can already be done by ln-service client-side for BOLT11 payment requests

**Comment by whiteyhat** [comment]
Hey @alexbosworth how is this fix going?

**Comment by alexbosworth** [comment]
I still don't really have a clear view of the reasoning about valid

**Comment by mandelmonkey** [comment]
I just asked on lnd slack to try and get an answer, but seems like the
param name valid is a bad choice

**Comment by mandelmonkey** [comment]
according to roasbeef

> the point of verify asserts that they actually have chans

https://lightningcommunity.slack.com/archives/C8S621RK6/p1563821189011100

**Comment by whiteyhat** [comment]
> according to roasbeef
> 
> > the point of verify asserts that they actually have chans
> 
> https://lightningcommunity.slack.com/archives/C8S621RK6/p1563821189011100

chans?

**Comment by mandelmonkey** [comment]
channels

**Comment by whiteyhat** [comment]
Oh... but if I want to verify a message and I do not mind about the node channels opened by a specific node. I think `LN-SERVICE` should grant me the option to decide 😃

**Comment by mandelmonkey** [comment]
i guess so, i'm still asking roasbeef about the reason why you would want
to know if the node has channels when verifying a signature

**Comment by alexbosworth** [comment]
You can't really decide unless I rewrite the verification portion

If you want to know if a node has channels you can do getNetworkGraph

**Comment by whiteyhat** [comment]
I guess the PR I did wasn’t valid right @alexbosworth ?

**Comment by alexbosworth** [comment]
I just don't really know why this valid thing is necessary in the method

If it's not necessary I think it should be removed from lnd

**Comment by whiteyhat** [comment]
Probably but at the moment, I think for this package it shouldn’t return an error if not valid https://github.com/alexbosworth/ln-service/issues/93#issuecomment-512903663

**Comment by alexbosworth** [comment]
ok I see what you're saying, I'll take another look

**Comment by whiteyhat** [comment]
> ok I see what you're saying, I'll take another look

Yes, I thought I was fixing with this pull request. But I don’t think so after all

**Comment by alexbosworth** [comment]
I think the `valid` flag is just confusing so I will ignore it completely

**Comment by mandelmonkey** [comment]
roasbeef said the valid flag is used in the case where verify message is used as 

> sybil protection, can’t fake channels

**Comment by alexbosworth** [comment]
If you really care about it, use the verifyMessage method along with the getNetworkGraph or getNodeInfo method so that you can check for associated chain-transactions

**Comment by mandelmonkey** [comment]
nope I dont just an fyi

**Pull request merged**
