### PR TITLE
Refactor grpc logic into node module

### PR DESCRIPTION
**Pull request by r0zar**
Move all the Lightning-related grpc functionality into its own npm module.

### CODE REVIEW

**Comment by r0zar** [comment]
Let me know your thoughts. :+1: I have you on the license in the module.

**Comment by alexbosworth** [comment]
Seems cool for later but I am not ready to abstract this stuff out yet because sometimes I am still messing with it, it's kind of unstable

**Comment by r0zar** [comment]
Reasonable. I'll mature it a bit and revisit the integration later. :+1:

**Comment by alexbosworth** [comment]
It would be interesting also for this to consider the native REST/websocket interface in LND - I don't know how that works and I don't know if there is documentation for it, but an NPM package for trying into that would be cool

**Pull request closed without merging**
