### PR TITLE
update proto type definitions for JS

### PR DESCRIPTION
**Pull request by bucko13**
addresses issue #103 and implements changes from [PR in lnrpc](https://github.com/lightningnetwork/lnd/pull/2352/files)

### CODE REVIEW

**Comment by bucko13** [comment]
My text editor automatically caught some formatting changes. Let me know if you'd like me to revert those.

**Comment by alexbosworth** [comment]
Is this a working solution for you instead of the undefined checks?

**Comment by alexbosworth** [comment]
It might be easier to merge without them, I have some updates coming on my side as well

**Comment by bucko13** [comment]
Still testing. Channels got force closed on my testnet so I'm waiting for new ones to get opened to test. The situation where the problem comes up is kind of a weird environment so not straightforward to test. 

> It might be easier to merge without them, I have some updates coming on my side as well
Merge without the styling?

**Comment by alexbosworth** [comment]
Yeah fewer changed lines is probably going to be easier for me to merge

**Comment by bucko13** [comment]
Updated 👍

Will confirm if it fixes #103 once the channels are opened.

**Comment by alexbosworth** [comment]
Cool let me know, potentially also this is a change that should be made also upstream to LND as in the issue I linked

**Comment by bucko13** [comment]
Unfortunately this did not seem to fix the issue I was having whereas payments went through with the undefined check.

**Comment by alexbosworth** [comment]
That's too bad, it would have been a cleaner solution

I'm not super excited about the undefined thing because it is pointing towards a bigger problem which is why do you get numbers for things marked as int64s? That will cause incorrect values sometimes

**Pull request closed without merging**
